### ISSUE TITLE
Package subpath './generators/app' is not defined by "exports"

### ISSUE THREAD

**Issue by gcdus** [jhipster/generator-jhipster-react-native#1095]
**Describe the bug**
Followed the instruction on Read me and got an error while executing following command inside the project directory.
jhipster --blueprints react-native
![jhipsterreactnative](https://user-images.githubusercontent.com/77105208/220803615-481d288f-7472-4f61-99c8-950a46c2541e.png)

The error file is attached.

**Instructions To reproduce**
Followed the instruction on Read me and got an error while executing following command inside the project directory.
jhipster --blueprints react-native

**JHipster app's `.yo-rc.json`**

The project is not generated by jhipster --blueprints react-native command, hence we do not have .yo-rc.json file available.

**Entity JDL or JSON files**
Not available

**Versions (please complete the following information):**

- JHipster React Native Version: Not sure how to get this.
- `hipster info` output:
-   Welcome to JHipster v7.9.3

Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
D:\Chetan\MyProjects\ilogicsApp
└── (empty)

```

cat: no such file or directory: .yo-rc.json

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

java version "11.0.12" 2021-07-20 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

git version 2.24.0.windows.2

node: v18.14.2

npm: 9.5.1

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

**Comment by mraible** [comment]
Can you try with Node 16 and see if it works?

**Comment by gcdus** [comment]
> Can you try with Node 16 and see if it works?

Thanks Matt, it is working with Node 16.

**Comment by mraible** [comment]
@gcdus I'm going to close this issue since Node 16 is expected for JHipster 7.
