### ISSUE TITLE
Image/File Blob Support

### ISSUE THREAD

**Issue by ruddell** [jhipster/generator-jhipster-react-native#204]
**Describe the bug**

Entity fields for ImageBlob and AnyBlob should have an image/file upload field rather than a text field.

**Instructions To reproduce**

Generate an entity with an ImageBlob and attempt to upload an image.

**Comment by ganadara135** [comment]
I know you are busy. Anyway I add my code for someone.
I deal with this problems like below.


----------------------- 'jhi-image-input.js' -----------------------------------------------

import React from 'react';
import { View, StyleSheet,  Text, Image } from 'react-native';
/* eslint-disable react-native/no-inline-styles */

export default React.forwardRef((props, ref) => {
  // const { label, labelStyle, error, ...otherProps } = props;
  const { label, labelStyle, error, inputType, contentType, value, testID, ...otherProps } = props;
  return (
    <View style={styles.container}>
      {/* if there's a label, render it */}
      {label && <Text style={[styles.label, labelStyle]}>{label}</Text>}
      {/* render the base64 image or plain image input */}      
      {inputType === 'image-base64' ?
      <Image ref={ref} style={[styles.imageBlob, { borderColor: error ? '#fc6d47' : '#c0cbd3' }]} 
        source={{ uri: `data:${contentType};base64,${value}`}}  /> : 
        <Image ref={ref} style={[styles.imageSize, { borderColor: error ? '#fc6d47' : '#c0cbd3' }]} 
        source={{ uri: `${value}` }}  />
      }
      {/* if there's an error, render it */}
      {!!error && !!error.message && <Text style={styles.textError}>{error && error.message}</Text>}
    </View>
  );
});

const styles = StyleSheet.create({
  imageBlob : {
    width: 100,
    height: 100,
  },
  imageSize : {
    width: 100,
    height: 100,
  },
  container: {
    marginVertical: 8,
  },
/*  input: {
    borderStyle: 'solid',
    borderWidth: 1,
    borderRadius: 5,
    backgroundColor: 'white',
    paddingVertical: 5,
    paddingLeft: 5,
    fontSize: 16,
    height: 40,
  },
  */
  label: {
    paddingVertical: 5,
    fontSize: 16,
    fontWeight: 'bold',
  },
  textError: {
    color: '#fc6d47',
    fontSize: 14,
  },
});


--------------------jhi-form-field.js------------------------------------------

import React from 'react';
import { useFormikContext } from 'formik';

import AppTextInput from './inputs/jhi-text-input';
import AppSwitchInput from './inputs/jhi-switch-input';
import AppListInput from './inputs/jhi-list-input';
import AppMultiListInput from './inputs/jhi-multi-list-input';
import AppDateInput from './inputs/jhi-date-input';
import AppImageInput from './inputs/jhi-image-input';
import { StyleSheet, Text } from 'react-native';
import ApplicationStyles from '../../themes/application.styles';

const styles = StyleSheet.create({
  ...ApplicationStyles.screen,
});

export default React.forwardRef((props, ref) => {
  let { name, inputType, ...otherProps } = props;
  const { setFieldTouched, setFieldValue, values, errors, touched } = useFormikContext();

  if (!inputType) {
    inputType = 'text';
  }
  if (!['text','boolean','number','date','datetime','select-one','select-multiple','image-base64','image'].includes(inputType)) {
    return <Text style={styles.errorText}>INVALID INPUT TYPE '{inputType}'</Text>;
  }

  // ensure fields are the correct format
  if (inputType === 'date' || (inputType === 'datetime' && !(values[name] instanceof Date))) {
    // date values can't be strings
    values[name] = new Date(values[name]);
  }
  if (inputType === 'boolean') {
    values[name] = Boolean(values[name]);
  }
  if (inputType === 'number' && (typeof values[name]).toLowerCase() === 'number') {
    // number values have to be strings
    values[name] = String(values[name]);
  }
  if (inputType === 'image-base64' || inputType === 'image' ) {
    // number values have to be strings
   // values[name] = String(values[name]);
  }

  const hasError = errors[name] && touched[name];
  return (
    <React.Fragment>
      {(!inputType || inputType === 'text') && (
        <AppTextInput
          ref={ref}
          value={values[name]}
          onChangeText={(text) => setFieldValue(name, text)}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {inputType === 'number' && (
        <AppTextInput
          ref={ref}
          keyboardType="numeric"
          value={values[name]}
          onChangeText={(text) => {
            const numberRegex = new RegExp(/^-?(\d*)?\.?(\d+)?$/);
            if (text.length === 0 || numberRegex.test(text.toString())) {
              setFieldValue(name, text);
            }
          }}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {inputType === 'boolean' && (
        <AppSwitchInput
          ref={ref}
          value={values[name]}
          onValueChange={(value) => setFieldValue(name, value)}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {inputType === 'select-one' && (
        <AppListInput
          ref={ref}
          value={values[name]}
          onValueChange={(value) => setFieldValue(name, value)}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {inputType === 'select-multiple' && (
        <AppMultiListInput
          ref={ref}
          value={values[name]}
          onSelectedItemsChange={(value) => setFieldValue(name, value)}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {(inputType === 'date' || inputType === 'datetime') && (
        <AppDateInput
          ref={ref}
          inputType={inputType}
          value={values[name]}
          selected={values[name]}
          onChange={(value) => setFieldValue(name, value)}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {(inputType === 'image-base64' || inputType === 'image') && (
        <AppImageInput
          ref={ref}
          inputType={inputType}
          value={values[name]}
          
          onChange={(value) => setFieldValue(name, value)}
          onBlur={() => setFieldTouched(name)}
          error={hasError}
          {...otherProps}
        />
      )}
      {hasError && <Text style={styles.errorText}>{errors[name]}</Text>}
    </React.Fragment>
  );
});

**Comment by mraible** [comment]
@DanielFran https://opencollective.com/generator-jhipster/expenses/92828

**Comment by pascalgrimaud** [comment]
@mraible : approved
