### ISSUE TITLE
Oauth2 build of react native jhipster login goes to NotFound page after hitting the login button in the react native app with the keycloak build.

### ISSUE THREAD

**Issue by jmoseman01** [jhipster/generator-jhipster-react-native#395]
**Describe the bug**
When clicking login with the keycloak build it goes from http://localhost:19006/start?authUrl="authUrl" immediately to 
http://localhost:19006/NotFound?authUrl="authUrl"

the authUrl seems to be valid when you navigate to it.  It just doesn't seem to be a valid route as /start?authUrl="<authUrl>"

**Instructions To reproduce**
Create a jhipster backend using keycloak for authentication
    "generator-jhipster": "7.0.1",
Create a jhipster react native app and use the previously created created backend while creating it

add the following to the src/main/docker/realm-config/jhipster-realm.json file's redirectUris array
http://localhost:19006

startup the keycloak docker container
docker-compose -f src/main/docker/keycloak.yml up

startup the jhipster backend
./mvnw

startup the react native app with expo
npm run start

**JHipster app's `.yo-rc.json`**

backend
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "applicationType": "monolith",
    "baseName": "oauth2jhipster",
    "jhipsterVersion": "7.0.1",
    "skipClient": false,
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1626137255767,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}

react native app
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "skipClient": false,
    "reactNative": {
      "reactNativeAppName": "carousel",
      "detox": false,
      "backend": "/home/jmo/projects/oauth2jhipster"
    },
    "applicationType": "monolith",
    "baseName": "oauth2jhipster",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1626137255767,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}

**Entity JDL or JSON files**

No JDL

**Versions (please complete the following information):**

- JHipster React Native Version: 
-     "generator-jhipster-react-native": "4.2.0",
- `jhipster info` output:
jmo@jmo-VirtualBox:~/projects/reactnativeOauth2$ jhipster info
INFO! Using JHipster version installed locally in current project's node_modules
Welcome to the JHipster Information Sub-Generator

##### **JHipster Version(s)**

```
carousel@0.0.1 /home/jmo/projects/reactnativeOauth2
└─┬ generator-jhipster-react-native@4.2.0
  └── generator-jhipster@7.1.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "blueprints": [],
    "otherModules": [],
    "skipClient": false,
    "reactNative": {
      "reactNativeAppName": "carousel",
      "detox": false,
      "backend": "/home/jmo/projects/oauth2jhipster"
    },
    "applicationType": "monolith",
    "baseName": "oauth2jhipster",
    "jhipsterVersion": "7.0.1",
    "skipServer": false,
    "skipUserManagement": true,
    "skipCheckLengthOfIdentifier": false,
    "skipFakeData": false,
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "testFrameworks": [],
    "pages": [],
    "creationTimestamp": 1626137255767,
    "serviceDiscoveryType": false,
    "reactive": false,
    "authenticationType": "oauth2",
    "packageName": "com.mycompany.myapp",
    "serverPort": "8080",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "buildTool": "maven",
    "serverSideOptions": ["websocket:spring-websocket"],
    "websocket": "spring-websocket",
    "searchEngine": false,
    "messageBroker": false,
    "enableSwaggerCodegen": false,
    "clientFramework": "angularX",
    "withAdminUi": true,
    "clientTheme": "none",
    "enableTranslation": false,
    "nativeLanguage": "en",
    "packageFolder": "com/mycompany/myapp",
    "clientPackageManager": "npm",
    "clientThemeVariant": "",
    "languages": ["en", "fr"]
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

git version 2.25.1

node: v14.17.0

npm: 6.14.13

Docker version 20.10.7, build f0df350

docker-compose version 1.26.2, build eefe0d31

No change to package.json was detected. No package manager install will be executed.
Congratulations, JHipster execution is complete!
Sponsored with ❤️  by @oktadev.

**Comment by ruddell** [comment]
Apologies for the extremely late reply.  I did some tests and it looks like this started after a major Expo version upgrade.  I'll try and get to this sometime this week/weekend, have to double check the Oauth code with the latest Expo docs.

Sadly OAuth isn't possible to test automatically with the E2E tests since the login page is rendered outside of the app (a Detox limitation).

**Comment by jmoseman01** [comment]
Thanks for doing this!
