### ISSUE TITLE
Fix Detox tests running in GitHub Actions

### ISSUE THREAD

**Issue by mraible** [jhipster/generator-jhipster-react-native#889]
**Describe the bug**

The Detox tests work just fine locally, but not on GitHub Actions with iOS. See https://github.com/wix/Detox/issues/3462#issuecomment-1234846538 for more information.

**Instructions To reproduce**

Run the iOS E2E action.

**Versions (please complete the following information):**

- JHipster React Native Version: `main`

**Comment by mraible** [comment]
I manually disabled the [iOS-E2E action](https://github.com/jhipster/generator-jhipster-react-native/actions/workflows/ios.yml). It'll need to be re-enabled to test this.

**Comment by zhyd1997** [comment]
@pascalgrimaud

bounty claimed: https://opencollective.com/generator-jhipster/expenses/188920
